<a href="https://colab.research.google.com/github/pks98/ExcelR_DS_Assignment/blob/main/model_building_using_rtitle_and_review.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
from sklearn.metrics import accuracy_score,precision_score

In [2]:
df=pd.read_csv('reviews.csv',usecols=['Review_Title','Reviews','Rating'])
df.head()

,Review_Title,Reviews,Rating
0,AWESOME...IN LOVE WITH IT !,Really impressed with the fastest delivery of ...,5.0
1,Enjoy while it lasts,This is the second time I am writing this revi...,2.0
2,Good,1. Quite good look2. Better noise cancellation...,4.0
3,not great,its a good set of ear buds but1. the quality o...,1.0
4,Best buds in the budget with Type C,I have been researching about getting a nice T...,5.0

In [4]:
df['text']=df['Review_Title']+" "+df['Reviews']

In [5]:
df.head()

,Review_Title,Reviews,Rating,text
0,AWESOME...IN LOVE WITH IT !,Really impressed with the fastest delivery of ...,5.0,AWESOME...IN LOVE WITH IT ! Really impressed w...
1,Enjoy while it lasts,This is the second time I am writing this revi...,2.0,Enjoy while it lasts This is the second time I...
2,Good,1. Quite good look2. Better noise cancellation...,4.0,Good 1. Quite good look2. Better noise cancell...
3,not great,its a good set of ear buds but1. the quality o...,1.0,not great its a good set of ear buds but1. the...
4,Best buds in the budget with Type C,I have been researching about getting a nice T...,5.0,Best buds in the budget with Type C I have bee...

In [6]:
df.isna().sum()

Review_Title      0
Reviews         103
Rating            0
text            103
dtype: int64

In [7]:
df.dropna(inplace=True)

In [8]:
def rating_classify(rating):
  if rating>=4:
    return 1
  else:
    return 0

In [9]:
df['label']=df['Rating'].apply(rating_classify)

In [10]:
df.head()

,Review_Title,Reviews,Rating,text,label
0,AWESOME...IN LOVE WITH IT !,Really impressed with the fastest delivery of ...,5.0,AWESOME...IN LOVE WITH IT ! Really impressed w...,1
1,Enjoy while it lasts,This is the second time I am writing this revi...,2.0,Enjoy while it lasts This is the second time I...,0
2,Good,1. Quite good look2. Better noise cancellation...,4.0,Good 1. Quite good look2. Better noise cancell...,1
3,not great,its a good set of ear buds but1. the quality o...,1.0,not great its a good set of ear buds but1. the...,0
4,Best buds in the budget with Type C,I have been researching about getting a nice T...,5.0,Best buds in the budget with Type C I have bee...,1

In [11]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [12]:
port_stem=PorterStemmer()
def text_processing(text):
  text=re.sub('[^a-zA-Z]',' ',text)
  text=text.lower()
  text=text.split()
  text = [port_stem.stem(word) for word in text if not word in stopwords.words('english')]
  text = ' '.join(text)
  return text

In [13]:
df['text']=df['text'].apply(text_processing)

In [14]:
df.head()

,Review_Title,Reviews,Rating,text,label
0,AWESOME...IN LOVE WITH IT !,Really impressed with the fastest delivery of ...,5.0,awesom love realli impress fastest deliveri am...,1
1,Enjoy while it lasts,This is the second time I am writing this revi...,2.0,enjoy last second time write review sure earli...,0
2,Good,1. Quite good look2. Better noise cancellation...,4.0,good quit good look better nois cancel good ba...,1
3,not great,its a good set of ear buds but1. the quality o...,1.0,great good set ear bud qualiti sound get bad c...,0
4,Best buds in the budget with Type C,I have been researching about getting a nice T...,5.0,best bud budget type c research get nice tw bu...,1

In [21]:
tf=TfidfVectorizer(max_features=3000)
x=tf.fit_transform(df['Reviews']).toarray()
y=df['label'].values

In [22]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

In [17]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier,BaggingClassifier,ExtraTreesClassifier,GradientBoostingClassifier
from xgboost import XGBClassifier

In [18]:
svc = SVC(kernel='sigmoid', gamma=1.0)
knc = KNeighborsClassifier()
mnb = MultinomialNB()
dtc = DecisionTreeClassifier(max_depth=5)
lrc = LogisticRegression(solver='liblinear', penalty='l1')
rfc = RandomForestClassifier(n_estimators=50, random_state=2)
abc = AdaBoostClassifier(n_estimators=50, random_state=2)
bc = BaggingClassifier(n_estimators=50, random_state=2)
etc = ExtraTreesClassifier(n_estimators=50, random_state=2)
gbdt = GradientBoostingClassifier(n_estimators=50,random_state=2)
xgb = XGBClassifier(n_estimators=50,random_state=2)

clfs = {
    'SVC' : svc,
    'KN' : knc, 
    'NB': mnb, 
    'DT': dtc, 
    'LR': lrc, 
    'RF': rfc, 
    'AdaBoost': abc, 
    'BgC': bc, 
    'ETC': etc,
    'GBDT':gbdt,
    'xgb':xgb
}

In [20]:
def train_classifier(clf,X_train,y_train,X_test,y_test):
    clf.fit(X_train,y_train)
    y_pred = clf.predict(X_test)
    accuracy = accuracy_score(y_test,y_pred)
    precision = precision_score(y_test,y_pred)
    
    return accuracy,precision

In [23]:
accuracy_scores = []
precision_scores = []

for name,clf in clfs.items():
    
    current_accuracy,current_precision = train_classifier(clf, x_train,y_train,x_test,y_test)
    
    accuracy_scores.append(current_accuracy)
    precision_scores.append(current_precision)

In [24]:
performance_df = pd.DataFrame({'Algorithm':clfs.keys(),'Accuracy':accuracy_scores,'Precision':precision_scores}).sort_values('Precision',ascending=False)

In [25]:
performance_df

   Algorithm  Accuracy  Precision
0        SVC  0.781250   0.782857
4         LR  0.769886   0.766854
8        ETC  0.767045   0.762570
2         NB  0.776989   0.760000
7        BgC  0.747159   0.757396
5         RF  0.764205   0.754098
10       xgb  0.745739   0.750725
9       GBDT  0.744318   0.745714
6   AdaBoost  0.715909   0.701058
3         DT  0.677557   0.700965
1         KN  0.681818   0.650943